# Generated by Django 3.0.8 on 2020-07-28 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('character_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField()),
                ('bids', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContractShipName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField()),
                ('ship_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_id', models.IntegerField()),
                ('planet_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StructureTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('timer_corp', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('timer_type', models.CharField(max_length=100)),
                ('structure_type_id', models.IntegerField()),
                ('structure_type_name', models.CharField(max_length=100)),
                ('structure_name', models.CharField(max_length=100)),
                ('structure_corp', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
