# Generated by Django 3.0.8 on 2020-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_id', models.IntegerField()),
                ('planet_name', models.CharField(max_length=100)),
            ],
        ),
    ]
