# Generated by Django 3.0.8 on 2020-07-24 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_planetname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField()),
                ('bids', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
